apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah-push
  namespace: tekton-ci
spec:
  description: Build the Docker image with Buildah and push it to Docker Hub.
  params:
    - name: image-name
      type: string
    - name: image-tag
      type: string
    - name: buildah-image
      type: string
      default: quay.io/buildah/stable:v1.38.0
  workspaces:
    - name: source
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-creds
  steps:
    - name: build-and-push
      image: $(params.buildah-image)
      workingDir: $(workspaces.source.path)/repo
      env:
        - name: HOME
          value: /tekton/home
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-config
          mountPath: /tekton/home/.docker
      script: |
        set -e

        DOCKER_CONFIG_PATH="/tekton/home/.docker"

        if [ -f "$DOCKER_CONFIG_PATH/.dockerconfigjson" ]; then
          USERNAME=$(sed -n 's/.*"username":"\([^"]*\)".*/\1/p' "$DOCKER_CONFIG_PATH/.dockerconfigjson" | head -n1)
          PASSWORD=$(sed -n 's/.*"password":"\([^"]*\)".*/\1/p' "$DOCKER_CONFIG_PATH/.dockerconfigjson" | head -n1)
        fi

        buildah --storage-driver=vfs bud \
          --format=docker \
          -f Dockerfile \
          -t "$(params.image-name):$(params.image-tag)" \
          .
        buildah --storage-driver=vfs push \
          --format=v2s2 \
          --creds "$USERNAME:$PASSWORD" \
          "$(params.image-name):$(params.image-tag)"
