---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: react-app
  namespace: flux-system
spec:
  image: uditdataxis12345/testing-proj-cicd
  interval: 30s
  secretRef:
    name: dockerhub-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: react-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: react-app
  filterTags:
    pattern: '^[0-9]{14}-[a-f0-9]{8}$'
    extract: '$0'
  policy:
    alphabetical:
      order: desc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: react-app
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcd-bot
        email: fluxcd-bot@users.noreply.github.com
      messageTemplate: "ci: update react-app image [skip ci]"
      signOff: false
    push:
      branch: main
      force: false
  update:
    strategy: Setters
    path: ./clusters/my-cluster/apps
    path: ./clusters/my-cluster/apps/react-app
